### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by timtnleeProject** [timtnleeProject/note#3]
# Screen, size

## @container query

`＠media` 是看螢幕大小，`@container` 可以看外層元素大小當臨界點

https://www.youtube.com/watch?v=rrLAg7xNERA&t=170s

```css
.container {
  container-type: inline-size;
}

@container (max-width: 500px) {
  .card {
    flex-direction: column;
  }
}
```

with name
```css
.container {
  container-type: inline-size;
  container-name: sidebar;
}

@container sidebar (max-width: 500px) {
  .card {
    flex-direction: column;
  }
}
```

container-type:
- inline-size: 只有水平方向, 高度隨內容自動增長
- size: 包含水平和垂直

在 container 裡面的元素可以用 container 相對單位 `cqw`, `cqh`
[(CSS_Container_Queries)](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries)

## vh, vw
https://www.youtube.com/watch?v=veEqYQlfNx8
### vw
-  vw 包含了右邊scrollbar(如果存在)，因此用 100vw 可能不準確，應該不用設置或用 100%
### vh
`100vh` 在行動裝置可能包含上面搜尋欄導致高度不如預期。
可以使用 
- `dvh`: dynamic viewport height 代表最小可視高度，但會隨著搜尋欄消失/出現改變高度。
- `svh`: small viewport height 代表最小可視高度。會使用有搜尋欄時候的 viewport 高度。

考慮瀏覽器兼容，可以使用
```css
.fullHeight {
  height: 100vh;
  height: 100svh; /* or dvh */
}
```

# font

## clamp

font-size 只用 `vw` 是 bad practice, 會使得字太小/太大，而且無法縮放。
可以用 clamp 限制最小和最大值。

```css
.profile {
  font-size: clamp(2rem, 3vw, 5rem);
}
```
